baseURL = "https://cjmathy.netlify.com/"
languageCode = "en-us"
title = "Chris Mathy"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/pages/about"
    weight = 2
    
[[menu.main]]
    name = "Research"
    url = "/pages/research"
    weight = 3
    
[[menu.main]]
    name = "Publications"
    url = "/pages/publications"
    weight = 4
    
[[menu.main]]
    name = "Contact"
    url = "/pages/contact"
    weight = 5

[params]
  google_analytics_id=""
  homepage_button_link = "https://www.biorxiv.org/content/10.1101/2020.01.04.893909v1"
  homepage_button_text = "Check out our new preprint!"
  # homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = "/images/gsp1_fig.jpg"

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Website built with Hugo and the Whisper Theme."
    meta_og_title = "Chris Mathy's site"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "/images/gsp1_fig.jpg"
    meta_og_description = "Website built with Hugo and the Whisper Theme."
    meta_twitter_card = "summary"
    meta_twitter_site = "@cjmathy"
    meta_twitter_creator = "@cjmathy"

  [params.logo]
      mobile = "/images/gsp1.gif"
      standard  = "/images/gsp1.gif"
      twitter = "/images/twitter.jpg"
      github = "/images/github.jpg"
      orcid = "/images/orcid.jpg"
      googlescholar = "/images/googlescholar.jpg"
      
[markup.goldmark.renderer] # this is needed to use raw html in markdown documents
    unsafe= true
