# Book settings
title: Christopher Mathy
  # author: Dr. Scientist
logo: ../resources/gsp1.gif

latex:
  latex_documents:
    targetname: book.tex

exclude_patterns: []

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 300

parse:
  myst_enable_extensions: 
    - smartquotes
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    # - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

home_page_in_navbar       : true

html:
  favicon                   : '../resources/gsp1.gif'  # A path to a favicon image
  google_analytics_id       : 'UA-155602879-1' 
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar

sphinx:
  config:
    templates_path: '_templates'
    html_theme: furo
    html_theme_options:
    # variables specific for the furo theme
      light_css_variables:
        color-code-background: '#f8f9fb'
      dark_css_variables:
        color-foreground-primary: '#f0f0f0'
        color-foreground-secondary: '#aba9a9'
        color-brand-primary: '#5996eb'
        color-brand-content: '#5996eb'
    

    
